# Shell variables
# Generated by 'wal'
wallpaper='/home/drago/wallpapers/anime/purple-sword.jpg'

# Special
background='#160814'
foreground='#c9bcb7'
cursor='#c9bcb7'

# Colors
color0='#160814'
color1='#5F4968'
color2='#9F2651'
color3='#BD2D53'
color4='#694B98'
color5='#97629E'
color6='#A25EC4'
color7='#c9bcb7'
color8='#8c8380'
color9='#5F4968'
color10='#9F2651'
color11='#BD2D53'
color12='#694B98'
color13='#97629E'
color14='#A25EC4'
color15='#c9bcb7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
